#!/usr/bin/env bash
set -euo pipefail

# Ensures metadata.yaml has a releaseSeries entry for the release tag's
# major.minor version. The tracked metadata.yaml is never modified in place:
# goreleaser refuses to release from a dirty working tree, and the release
# checkout is a detached tag anyway. Instead the up-to-date file is staged at
# _artifacts/metadata.yaml (which goreleaser attaches to the GitHub release)
# and a pull request adding the entry to main is opened.

BASE_BRANCH="main"
CONTRACT="v1beta2"
SKIP_PR=false
TAG=""

usage() {
  cat <<EOF
Ensure metadata.yaml has a releaseSeries entry for a release tag.

Checks metadata.yaml for a releaseSeries entry matching the tag's major.minor
and stages the up-to-date file at _artifacts/metadata.yaml for goreleaser to
attach to the GitHub release. If the entry is missing, it is appended to the
staged copy and a pull request adding it to ${BASE_BRANCH} is opened (requires
the gh CLI, authenticated via GH_TOKEN/GITHUB_TOKEN).

Usage:
  $(basename "$0") [flags] <tag>

Args:
  <tag>            release tag being cut, e.g. v0.2.0

Flags:
  -c, --contract   CAPI contract version for a new entry (default: ${CONTRACT})
      --skip-pr    stage the updated metadata only; do not open a pull request
  -h, --help       show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -c|--contract)
      [[ $# -ge 2 ]] || { echo "error: $1 requires a value" >&2; exit 1; }
      CONTRACT="$2"
      shift 2
      ;;
    --skip-pr)
      SKIP_PR=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "error: unknown flag: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      [[ -z "$TAG" ]] || { echo "error: unexpected argument: $1" >&2; usage >&2; exit 1; }
      TAG="$1"
      shift
      ;;
  esac
done

[[ -n "$TAG" ]] || { echo "error: missing <tag>" >&2; usage >&2; exit 1; }
if [[ ! "$TAG" =~ ^v([0-9]+)\.([0-9]+)\.[0-9]+ ]]; then
  echo "error: tag \"${TAG}\" is not in vX.Y.Z form" >&2
  exit 1
fi
MAJOR="${BASH_REMATCH[1]}"
MINOR="${BASH_REMATCH[2]}"

cd "$(git rev-parse --show-toplevel)"

has_entry() {
  awk -v major="$MAJOR" -v minor="$MINOR" '
    $1 == "-" && $2 == "major:" { m = $3 }
    $1 == "minor:" && m == major && $2 == minor { found = 1 }
    END { exit !found }
  ' "$1"
}

append_entry() {
  cat >>"$1" <<EOF
  - major: ${MAJOR}
    minor: ${MINOR}
    contract: ${CONTRACT}
EOF
}

mkdir -p _artifacts
cp metadata.yaml _artifacts/metadata.yaml

if has_entry _artifacts/metadata.yaml; then
  echo "metadata.yaml already has a releaseSeries entry for ${MAJOR}.${MINOR}"
  exit 0
fi

append_entry _artifacts/metadata.yaml
echo "staged releaseSeries entry for ${MAJOR}.${MINOR} (contract ${CONTRACT}) at _artifacts/metadata.yaml"

if [[ "$SKIP_PR" == true ]]; then
  echo "--skip-pr: not opening a pull request; remember to add the entry to metadata.yaml"
  exit 0
fi

command -v gh >/dev/null || { echo "error: gh CLI is required to open the pull request (or pass --skip-pr)" >&2; exit 1; }

BRANCH="metadata-release-series-${MAJOR}.${MINOR}"
git fetch --quiet origin "$BASE_BRANCH"

worktree="$(mktemp -d)"
trap 'git worktree remove --force "$worktree" >/dev/null 2>&1 || true' EXIT
git worktree add --quiet -B "$BRANCH" "$worktree" "origin/${BASE_BRANCH}"

if has_entry "${worktree}/metadata.yaml"; then
  echo "${BASE_BRANCH} already has the ${MAJOR}.${MINOR} entry; no pull request needed"
  exit 0
fi
append_entry "${worktree}/metadata.yaml"

# Fall back to the github-actions bot identity when running in CI.
GIT_NAME="$(git config user.name 2>/dev/null || echo 'github-actions[bot]')"
GIT_EMAIL="$(git config user.email 2>/dev/null || echo '41898282+github-actions[bot]@users.noreply.github.com')"
git -C "$worktree" -c "user.name=${GIT_NAME}" -c "user.email=${GIT_EMAIL}" \
  commit --quiet -m "Add ${MAJOR}.${MINOR} release series to metadata.yaml" metadata.yaml
git -C "$worktree" push --quiet --force origin "$BRANCH"

if [[ "$(gh pr list --head "$BRANCH" --base "$BASE_BRANCH" --state open --json number --jq length)" == "0" ]]; then
  gh pr create --head "$BRANCH" --base "$BASE_BRANCH" \
    --title "Add ${MAJOR}.${MINOR} release series to metadata.yaml" \
    --body "Auto-generated by hack/ensure-capi-metadata.sh while releasing ${TAG}.

The ${TAG} release was cut without a releaseSeries entry for the ${MAJOR}.${MINOR} series; the release asset was published with this entry included (contract ${CONTRACT}), and this PR syncs it back to ${BASE_BRANCH}."
else
  echo "pull request from ${BRANCH} is already open"
fi
